name: Deploy to PROD

on:
  push:
    paths:
      - 'prod/**'
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply PROD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./prod

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: ./prod

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: ./prod

