name: Terraform Provision - Dev

on:
  push:
    paths:
      - 'envs/dev/**'
      - 'modules/s3_bucket/**'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    name: 'Terraform Plan & Apply (Dev)'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./envs/dev
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./envs/dev
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./envs/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./envs/dev
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        working-directory: ./envs/dev
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

